#!/hint/zsh
# Cycle through groups
# Example usage:
#   zstyle ':fzf-tab:*' fzf-command ftb-group-cycle
#   zstyle ':fzf-tab:*' ftb-group-cycle-trigger - =
#   zstyle ':fzf-tab:*' ftb-group-cycle-command ftb-tmux-popup
emulate -L zsh -o extended_glob

# get number of header lines
local header_lines=${${(M)@:#--header-lines=*}#*=}

# write completion list to file
cat > $tmp_dir/cycle-list-$$

# get configuration
local fzf_command trigger
zstyle -s ":fzf-tab:$_ftb_curcontext" ftb-group-cycle-command fzf_command || fzf_command=fzf
zstyle -s ":fzf-tab:$_ftb_curcontext" ftb-group-cycle-trigger trigger || trigger=(- =)

# call fzf with custom reload command
local reload_command="$commands[zsh] $FZF_TAB_HOME/lib/ftb-group-cycle-command $$ $header_lines $tmp_dir"
$fzf_command $@ --bind="${trigger[1]}:reload($reload_command -1),${trigger[2]}:reload($reload_command 1)" < $tmp_dir/cycle-list-$$

# clean up
rm -f $tmp_dir/cycle-list-$$
