#!/hint/zsh
# A part of ftb-group-cycle

# receive arguments
local pid=$1 header_lines=$2 tmp_dir=$3 offset=$@[-1]

# read completion list
local -a list=(${(f)"$(<$tmp_dir/cycle-list-$pid)"})

# print headers
if (( header_lines != 0 )); then
  print -l $list[1,header_lines]
fi

# get total group count
local -Ua total=(${(f)"$(print -l ${list:$header_lines} | grep -a -oP '^\x1b\[[0-9;]*m')"})

# get current group index, start from 2
local current=2
if [[ -f $tmp_dir/cycle-current-$pid ]]; then
  current=$(( $(<$tmp_dir/cycle-current-$pid) + offset ))
fi
(( current > $#total )) && current=1
echo $current > $tmp_dir/cycle-current-$pid

# print current group
print -l ${list:$header_lines} | grep -a -F "${total[current]}"
