name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Initialize
        run: sudo apt-get install zsh

      - name: Run test
        run: cd test && zsh runtests.zsh fzftab.ztst

